### ISSUE TITLE
Reach a larger audience with a recurring Webinar

### ISSUE THREAD

**Issue by ProfJanetDavis** [ProfJanetDavis/cra-student-resources#11]
The [National Center for Faculty Development & Diversity](https://www.facultydiversity.org/) provides a good model. They have a curriculum of several slide decks that they do a Webinar on seasonally or annually. You can attend the live webinar or watch a recording asynchronously.

This does not strictly depend on #3.
See also #6, #7 

- [x] Choose a date, time, technology
- [x] Ask CERP for help with assessing the Webinar and unmet needs 
- [x] Ask Nicole for help with advertising via CRA channels; also Twitter and SIGCSE-members
- [x] Customize the slide deck for this general "undergrads on the Web" audience, starting with the PRE.CISE version of the talk.
- [x] Deliver and record the talk
- [x] Post the recorded video on the CONQUER web site

**Comment by ian-ludden** [comment]
Consider using Zoom Webinar for easy Q&A with large audience

> What is Webinar?
> Zoom Video Webinars allow you to easily conduct large online events with video, audio and screen sharing for up to 100 video participants and 10,000 attendees
> The features in Webinar are tailored for managing large audiences with branding, registration, host controls, polls, question & answer, raise hand, chat, recording and reporting
> Monetize your webinars with our Paypal integration (via Zapier)
